alias ll='ls -lah --color=auto'
alias be='bundle exec'
alias df='df -h'
alias rm='rm -iv'
alias cp='cp -iv'
alias mv='mv -iv'
alias pp='ps auxf | pager'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias size='du -sh'
alias chrome='/usr/bin/google-chrome-stable --disk-cache-dir=/tmp --cipher-suite-blacklist=0x0004,0x0005'
alias google-chrome='/usr/bin/google-chrome-stable --disk-cache-dir=/tmp --cipher-suite-blacklist=0x0004,0x0005'
alias tree='tree -C'
alias activate='source venv/bin/activate'
alias links2='links2 -g'
alias liferea='liferea -w shown'
alias serve='ruby -run -e httpd . -p 9090'
alias now='date +"%T %Z"'
alias aliases='pager ~/.bash/aliases.sh'
alias pdfview='evince -w'
alias myip='curl https://diagnostic.opendns.com/myip 2> /dev/null | ruby -e "puts ARGF.read"'
alias bat='upower -i $(upower -e | grep BAT) | egrep "state|time|percentage"'
