export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LANG=en_US.UTF-8
export TERM=xterm-256color
export TZ=Europe/Berlin
export EDITOR=vim
export HOSTNAME=$(uname -n)
export SYNCNAME=$(uname -n)
export REMOTEDNS=true
export CLIPBOARDEVENTS=false
export AUTOREFRESH=false
export CONCURRENCY_LEVEL=4
export MAKEFLAGS="-j4"
export HISTSIZE=2000
export HISTFILESIZE=2000
export HISTCONTROL=ignoreboth
export PERL_MB_OPT="--install_base \"${HOME}/perl5\""
export PERL_MM_OPT="INSTALL_BASE=${HOME}/perl5"
export NVM_DIR="$HOME/.nvm"
export PATH=/opt/xtensa-lx106/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH=$HOME/node_modules/.bin:$PATH
export PATH=$HOME/perl5/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH="$HOME/.linuxbrew/bin:$PATH"
export PATH="$HOME/.linuxbrew/sbin:$PATH"
export PATH=$HOME/.rvm/bin:$PATH
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
export XDG_CACHE_HOME=/tmp
export XDG_DATA_DIRS=/usr/share
export XDG_DATA_DIRS="${HOME}/.linuxbrew/share:${XDG_DATA_DIRS}"
export ZSH="/home/manuel/.oh-my-zsh"
